# Generated by Django 4.1.3 on 2022-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='annualpack',
            field=models.FloatField(),
        ),
    ]
